version: '3'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dev
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql
      - ./create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql